# Generated by Django 5.0.7 on 2024-07-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='when_formed',
            field=models.DateField(blank=True, null=True, verbose_name='Formation Date'),
        ),
    ]
