# Generated by Django 5.0.7 on 2024-07-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Branch Id')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Service Name')),
                ('pan', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PAN / VAT No')),
                ('crid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Company Registration ID')),
                ('pro', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Company Representative')),
                ('seating_capacity', models.PositiveBigIntegerField(verbose_name='Seating Capacity')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('district', models.CharField(default='Random Street', max_length=100, verbose_name='District')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street_add', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone Number')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Branch Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
