# Generated by Django 5.0.7 on 2024-07-30 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('sales', '0002_invoice_is_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complementary'), ('pl', 'Pay Later'), ('sp', 'Split Payment'), ('paid', 'paid')], default='p', max_length=100),
        ),
        migrations.CreateModel(
            name='OrderBilling',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complementary'), ('pl', 'Pay Later'), ('sp', 'Split Payment'), ('paid', 'paid')], default='p', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_billing', to='orders.order', verbose_name='Order')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sale', verbose_name='sales_order_to_order_billing')),
            ],
        ),
    ]
