# Generated by Django 5.0.7 on 2024-07-30 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_payment_status_orderbilling'),
        ('sales', '0003_remove_customerpayment_bank_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.sale', verbose_name='sales_order_to_order'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.saleitem', verbose_name='sales_order_to_order_item'),
        ),
        migrations.DeleteModel(
            name='OrderBilling',
        ),
    ]
