# Generated by Django 5.0.7 on 2024-07-25 05:06

import accounting.models
import core.userSession
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('acc_type', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='Bank', max_length=100, verbose_name='Bank/Cash')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('type', models.CharField(blank=True, choices=[('savings', 'Savings'), ('current', 'Current')], max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user_add', models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Accounts',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='CashTransfers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bill_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.FloatField(default=1)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('paid_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_paid_from', to='accounting.bankaccounts')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to_account', to='accounting.bankaccounts')),
                ('user_add', models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Transfer',
                'verbose_name_plural': 'Cash Transfers',
            },
        ),
        migrations.CreateModel(
            name='ChartofAccounts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('coa_type', models.CharField(choices=[('Assets', 'Assets'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Income', 'Income'), ('Expenses', 'Expenses')], default='Assets', max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='accounting.chartofaccounts')),
                ('user_add', models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
            },
        ),
        migrations.CreateModel(
            name='ChequeRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_name', models.CharField(max_length=255)),
                ('cheque_no', models.CharField(max_length=50)),
                ('issued_date', models.DateField()),
                ('status', models.CharField(choices=[('cleared', 'Cleared'), ('pending', 'Pending'), ('partial', 'Partial'), ('bounced', 'Bounced')], default='pending', max_length=10)),
                ('cheque_type', models.CharField(choices=[('recieved', 'Cheque Recieved'), ('issued', 'Cheque Issued')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='accounting.bankaccounts')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('user_add', models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque Register',
                'verbose_name_plural': 'Cheque Register',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Currency Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('decimal_places', models.PositiveBigIntegerField(default=2, verbose_name='Decimal Places')),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user_add', models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.AddField(
            model_name='bankaccounts',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounting.currency'),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('jounral_entry_no', models.CharField(blank=True, default=accounting.models.generate_custom_journal, max_length=65, null=True)),
                ('bill_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user_add', models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
            },
        ),
        migrations.CreateModel(
            name='JournalEntryItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dr_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cr_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('chart_of_accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.chartofaccounts')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry')),
                ('user_add', models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry Items',
                'verbose_name_plural': 'Journal Entry Items',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user_add', models.ForeignKey(default=core.userSession.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
