# Generated by Django 5.0.7 on 2024-07-31 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_chartofaccounts_opening_balace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartofaccounts',
            old_name='opening_balace',
            new_name='opening_balance',
        ),
    ]
