# Generated by Django 5.0.7 on 2024-07-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
